# Generated by Django 4.1.6 on 2024-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0008_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='popularity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
