# Generated by Django 4.1.6 on 2024-10-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0009_line_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='preview',
        ),
    ]
