# Generated by Django 4.2.16 on 2024-10-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0010_remove_line_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
