# Generated by Django 4.2.16 on 2024-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0011_line_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='photo',
        ),
        migrations.AddField(
            model_name='line',
            name='previewPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='preview_photos/'),
        ),
    ]
