# Generated by Django 4.1.6 on 2024-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0009_alter_line_popularity'),
        ('Constructor', '0012_remove_line_photo_line_previewphoto'),
    ]

    operations = [
    ]
