# Generated by Django 4.1.6 on 2024-10-25 15:32

import Constructor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0013_merge_20241024_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='previewPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=Constructor.models.generate_uuid_filename),
        ),
    ]
