# Generated by Django 4.1.6 on 2024-10-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0015_group_created_at_group_updated_at_line_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='route_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Constructor.line'),
        ),
    ]
