# Generated by Django 4.2 on 2024-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0017_group_activity_description_group_trip_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privacy_setting',
            field=models.CharField(choices=[('closed', 'Закрытая группа'), ('link', 'Доступная по ссылке'), ('private', 'Приватная')], default='closed', max_length=10),
        ),
    ]
