# Generated by Django 4.2 on 2024-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0019_alter_group_privacy_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activity_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
