# Generated by Django 4.2 on 2024-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0020_alter_group_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='privacy_setting',
            field=models.CharField(choices=[('open', 'Открытая группа'), ('link', 'Доступная по ссылке'), ('private', 'Закрытая')], default='open', max_length=10),
        ),
    ]
