# Generated by Django 4.2 on 2024-11-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constructor', '0023_alter_group_options_alter_line_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание маршрута'),
        ),
    ]
