# Generated by Django 4.1.6 on 2024-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0011_portfolioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personal_photo',
            field=models.ImageField(blank=True, default='profile_photos/anon.png', null=True, upload_to='profile_photos/'),
        ),
    ]
