# Generated by Django 4.1.6 on 2024-10-13 16:22

import Userprofile.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0014_alter_userprofile_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personal_photo',
            field=models.ImageField(blank=True, default='profile_photos/anon.png', null=True, upload_to=Userprofile.utils.user_profile_photo_path),
        ),
    ]
