# Generated by Django 4.1.6 on 2024-10-22 15:10

import Userprofile.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0015_alter_userprofile_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to=Userprofile.utils.portfolio_image_path),
        ),
    ]
