# Generated by Django 4.2 on 2024-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0016_alter_portfolioimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Открытый'), ('closed', 'Закрытый')], default='open', max_length=10),
        ),
    ]
