# Generated by Django 4.2 on 2024-11-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0017_userprofile_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'verbose_name': 'Фотография портфолио', 'verbose_name_plural': 'Фотографии портфолио'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
